[model]
em_iter = 4
em_burn = 2
mc_iter = 300
mc_burn = 150
stepsize = 0.01
perturbation = 0.05
replicates = 5
base_taxa = 0

[io]
count_table = "./test_files/wide/wide_count_table.csv"
sample_data = "./test_files/wide/wide_sample_data.csv"
output = "./test_files/wide/wide_divnet_output.csv"

[misc]
random_seed = 0
